apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-test
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gold